-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dump della struttura del database musei_torino
CREATE DATABASE IF NOT EXISTS `musei_torino` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `musei_torino`;

DROP TABLE IF EXISTS `artefatto`;
DROP TABLE IF EXISTS `museo`;

-- Dump della struttura di tabella musei_torino.museo
CREATE TABLE IF NOT EXISTS museo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipologia VARCHAR(100)
);

-- Dump dei dati della tabella musei_torino.museo: ~14 rows (circa)
/*!40000 ALTER TABLE `museo` DISABLE KEYS */;
INSERT INTO `museo` (nome, tipologia) VALUES
('Museo Egizio', 'Archeologico'),
('Museo Nazionale del Cinema', 'Multimediale'),
('Museo d’Arte Orientale (MAO)', 'Artistico'),
('GAM - Galleria Civica d’Arte Moderna e Contemporanea', 'Artistico'),
('Museo Nazionale dell’Automobile', 'Storico'),
('Museo Nazionale del Risorgimento Italiano', 'Storico'),
('Palazzo Madama - Museo Civico d’Arte Antica', 'Artistico'),
('Museo della Montagna Duca degli Abruzzi', 'Etnografico'),
('Museo Pietro Micca e dell’Assedio di Torino del 1706', 'Storico'),
('Museo di Anatomia Umana Luigi Rolando', 'Scientifico'),
('Museo di Antropologia Criminale Cesare Lombroso', 'Scientifico'),
('Museo della Sindone', 'Religioso'),
('Museo Ferroviario Piemontese', 'Tecnologico');
/*!40000 ALTER TABLE `museo` ENABLE KEYS */;

-- Dump della struttura di tabella musei_torino.artefatto
CREATE TABLE IF NOT EXISTS `artefatto` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipologia VARCHAR(100),
    epoca VARCHAR(100),
    id_museo INT,
    FOREIGN KEY (id_museo) REFERENCES museo(id)
);

-- Dump dei dati della tabella musei_torino.artefatto: ~650 rows (circa)
/*!40000 ALTER TABLE `artefatto` DISABLE KEYS */;
INSERT INTO artefatto (nome, tipologia, epoca, id_museo) VALUES
-- Museo Egizio (id_museo = 1) ~50 rows
('Statua di Cheope', 'Scultura', 'XXVII secolo a.C.', 1),
('Papiro del Libro dei Morti di Kha', 'Manoscritto', 'XIV secolo a.C.', 1),
('Maschera funeraria di sacerdote', 'Manufatto funerario', 'VII secolo a.C.', 1),
('Amuleto a forma di scarabeo', 'Gioiello', 'XII secolo a.C.', 1),
('Stele di Horus', 'Reperto lapideo', 'XII secolo a.C.', 1),
('Statua di Ramses II', 'Scultura', 'XIII secolo a.C.', 1),
('Canopo di Iuefankh', 'Ceramica funeraria', 'VII secolo a.C.', 1),
('Testa di Cleopatra VII', 'Scultura', 'I secolo a.C.', 1),
('Pettorale d’oro di Tutankhamon', 'Gioiello', 'XIV secolo a.C.', 1),
('Statua di Sekhmet', 'Scultura', 'XIV secolo a.C.', 1),
('Sarcofago di Butehamon', 'Manufatto funerario', 'XI secolo a.C.', 1),
('Papiro di Ani', 'Manoscritto', 'XIII secolo a.C.', 1),
('Usciabti di Kha', 'Manufatto funerario', 'XIV secolo a.C.', 1),
('Tavoletta di offerte di Ramses III', 'Reperto lapideo', 'XII secolo a.C.', 1),
('Anello con il nome di Thutmose III', 'Gioiello', 'XV secolo a.C.', 1),
('Frammento di rilievo con Amon-Ra', 'Reperto lapideo', 'XIII secolo a.C.', 1),
('Vaso canopo di Hori', 'Ceramica funeraria', 'XI secolo a.C.', 1),
('Statuetta di Iside con Horus bambino', 'Scultura', 'VI secolo a.C.', 1),
('Tavoletta magica con iscrizioni geroglifiche', 'Manufatto rituale', 'VII secolo a.C.', 1),
('Pendente a forma di Occhio di Horus', 'Gioiello', 'IX secolo a.C.', 1),
('Maschera funeraria di uomo', 'Manufatto funerario', 'VIII secolo a.C.', 1),
('Sarcofago di Petamon', 'Manufatto funerario', 'VII secolo a.C.', 1),
('Statua di scriba seduto', 'Scultura', 'V secolo a.C.', 1),
('Bassorilievo con scena di offerta a Osiride', 'Reperto lapideo', 'XII secolo a.C.', 1),
('Papiro con formule magiche', 'Manoscritto', 'X secolo a.C.', 1),
('Amuleto della dea Bastet', 'Gioiello', 'VIII secolo a.C.', 1),
('Modello di barca funeraria', 'Manufatto funerario', 'XII secolo a.C.', 1),
('Statuetta di Anubi', 'Scultura', 'VII secolo a.C.', 1),
('Tavoletta votiva a Thot', 'Reperto lapideo', 'IX secolo a.C.', 1),
('Collana di perle di faience', 'Gioiello', 'XV secolo a.C.', 1),
('Coppa con iscrizioni geroglifiche', 'Ceramica decorata', 'XIII secolo a.C.', 1),
('Cofanetto di legno intarsiato', 'Manufatto d’uso', 'XII secolo a.C.', 1),
('Stele funeraria di Neferrenpet', 'Reperto lapideo', 'XII secolo a.C.', 1),
('Scettro cerimoniale di alabastro', 'Manufatto rituale', 'XIV secolo a.C.', 1),
('Papiro astronomico', 'Manoscritto', 'XI secolo a.C.', 1),
('Bracciale d’oro con iscrizioni', 'Gioiello', 'XIV secolo a.C.', 1),
('Statua di Osiride', 'Scultura', 'X secolo a.C.', 1),
('Usciabti di Sethi I', 'Manufatto funerario', 'XIII secolo a.C.', 1),
('Tavoletta votiva di Hathor', 'Reperto lapideo', 'XI secolo a.C.', 1),
('Specchio in bronzo con manico di legno', 'Oggetto d’uso', 'XII secolo a.C.', 1),
('Vaso rituale per offerte', 'Ceramica rituale', 'XI secolo a.C.', 1),
('Statua di Horus falco', 'Scultura', 'X secolo a.C.', 1),
('Cofanetto per cosmetici', 'Manufatto d’uso', 'XIV secolo a.C.', 1),
('Amuleto del pilastro Djed', 'Gioiello', 'XII secolo a.C.', 1),
('Sarcofago di Taia', 'Manufatto funerario', 'XI secolo a.C.', 1),
('Stele con scena di adorazione di Ra', 'Reperto lapideo', 'XII secolo a.C.', 1),
('Papiro con inni ad Aton', 'Manoscritto', 'XIV secolo a.C.', 1),
('Statuetta di Thot ibis', 'Scultura', 'VII secolo a.C.', 1),
('Maschera funeraria di donna', 'Manufatto funerario', 'VI secolo a.C.', 1),
('Anello sigillo di Amenhotep II', 'Gioiello', 'XV secolo a.C.', 1),
('Tavoletta con formule religiose', 'Reperto lapideo', 'XIII secolo a.C.', 1),

-- Museo Nazionale del Cinema (id_museo = 2) ~50 rows
('Macchina da presa Lumière', 'Strumento cinematografico', 'XIX secolo', 2),
('Lanterna magica', 'Strumento ottico', 'XIX secolo', 2),
('Proiettore Pathé Baby', 'Strumento cinematografico', 'XX secolo', 2),
('Pellicola originale di "Cabiria"', 'Pellicola', 'XX secolo', 2),
('Locandina di “La Dolce Vita”', 'Poster', 'XX secolo', 2),
('Oscar a Vittorio De Sica', 'Premio', 'XX secolo', 2),
('Telecamera Super8 Kodak', 'Strumento tecnologico', 'XX secolo', 2),
('Sceneggiatura di Michelangelo Antonioni', 'Documento', 'XX secolo', 2),
('Proiettore Cinemeccanica Victoria 8', 'Strumento cinematografico', 'XX secolo', 2),
('Manifesto di “Metropolis”', 'Poster', 'XX secolo', 2),
('Macchina fotografica Pathé Frères', 'Strumento ottico', 'XIX secolo', 2),
('Cinepresa Bolex H16', 'Strumento cinematografico', 'XX secolo', 2),
('Bobina originale di “Roma città aperta”', 'Pellicola', 'XX secolo', 2),
('Targa del Festival di Cannes a Fellini', 'Premio', 'XX secolo', 2),
('Scenografia in miniatura di “Cabiria”', 'Modello scenico', 'XX secolo', 2),
('Costume di scena di “Satyricon”', 'Costume', 'XX secolo', 2),
('Locandina di “8½”', 'Poster', 'XX secolo', 2),
('Proiettore portatile Ernemann', 'Strumento cinematografico', 'XX secolo', 2),
('Macchina da presa Mitchell BNC', 'Strumento cinematografico', 'XX secolo', 2),
('Taccuino di appunti di Dario Argento', 'Documento', 'XX secolo', 2),
('Pellicola sperimentale di Brakhage', 'Pellicola', 'XX secolo', 2),
('Cinepresa Arriflex 35 IIC', 'Strumento cinematografico', 'XX secolo', 2),
('Premio David di Donatello a Sophia Loren', 'Premio', 'XX secolo', 2),
('Poster di “Nuovo Cinema Paradiso”', 'Poster', 'XX secolo', 2),
('Storyboard originale di “Il Gattopardo”', 'Documento', 'XX secolo', 2),
('Proiettore 16mm Bell & Howell', 'Strumento cinematografico', 'XX secolo', 2),
('Cinepresa tascabile Minolta Autopak 8', 'Strumento tecnologico', 'XX secolo', 2),
('Script autografo di “Amarcord”', 'Documento', 'XX secolo', 2),
('Fotogramma colorato a mano di “Viaggio nella Luna”', 'Pellicola', 'XIX secolo', 2),
('Telecamera digitale Sony DCR-VX1000', 'Strumento tecnologico', 'XX secolo', 2),
('Premio Nastro d’Argento a Roberto Benigni', 'Premio', 'XX secolo', 2),
('Locandina di “Rocco e i suoi fratelli”', 'Poster', 'XX secolo', 2),
('Fotocamera stereoscopica di Jules Richard', 'Strumento ottico', 'XIX secolo', 2),
('Cinepresa Panavision Panaflex', 'Strumento cinematografico', 'XX secolo', 2),
('Proiettore IMAX 70mm', 'Strumento cinematografico', 'XX secolo', 2),
('Maschera di scena di “Nosferatu”', 'Oggetto scenico', 'XX secolo', 2),
('Modello di macchina da presa Lumière in legno', 'Riproduzione storica', 'XX secolo', 2),
('Manoscritto di sceneggiatura di “Ladri di biciclette”', 'Documento', 'XX secolo', 2),
('Premio Oscar a Ennio Morricone', 'Premio', 'XXI secolo', 2),
('Telecamera HD RED One', 'Strumento tecnologico', 'XXI secolo', 2),
('Poster di “Blade Runner”', 'Poster', 'XX secolo', 2),
('Pellicola 70mm di “Lawrence d’Arabia”', 'Pellicola', 'XX secolo', 2),
('Tavola di storyboard di “Profondo Rosso”', 'Documento', 'XX secolo', 2),
('Proiettore a manovella Gaumont', 'Strumento cinematografico', 'XIX secolo', 2),
('Costume originale di “Il Conformista”', 'Costume', 'XX secolo', 2),
('Telecamera digitale Canon XL1', 'Strumento tecnologico', 'XX secolo', 2),
('Copia restaurata di “L’inferno” (1911)', 'Pellicola', 'XX secolo', 2),
('Targa celebrativa del Museo Nazionale del Cinema', 'Oggetto commemorativo', 'XX secolo', 2),
('Cinepresa Eumig C3M', 'Strumento cinematografico', 'XX secolo', 2),
('Manifesto di “La strada”', 'Poster', 'XX secolo', 2),
('Proiettore digitale Barco DP4K', 'Strumento cinematografico', 'XXI secolo', 2),

-- MAO - Museo d’Arte Orientale (id_museo = 3) ~50 rows
('Statua del Buddha Gandhara', 'Scultura', 'I secolo a.C.', 3),
('Moneta della dinastia Han', 'Numismatica', 'II secolo a.C.', 3),
('Vaso cinese in porcellana', 'Ceramica', 'XV secolo', 3),
('Spada Katana', 'Arma tradizionale', 'XVII secolo', 3),
('Paravento giapponese Byōbu', 'Arredo artistico', 'XVII secolo', 3),
('Maschera tibetana rituale', 'Maschera', 'XVIII secolo', 3),
('Stampa ukiyo-e di Hokusai', 'Stampa', 'XIX secolo', 3),
('Tamburo cerimoniale birmano', 'Strumento musicale', 'XIX secolo', 3),
('Buddha in bronzo thailandese', 'Scultura', 'XVII secolo', 3),
('Anfora persiana smaltata', 'Ceramica', 'XVI secolo', 3),
('Rotolo calligrafico cinese', 'Manoscritto', 'XVIII secolo', 3),
('Statuetta di Avalokiteshvara', 'Scultura', 'XII secolo', 3),
('Elmo samurai kabuto', 'Arma tradizionale', 'XVI secolo', 3),
('Maschera del teatro Nō', 'Maschera', 'XVII secolo', 3),
('Campana rituale tibetana', 'Strumento rituale', 'XVIII secolo', 3),
('Tappeto persiano', 'Tessuto artistico', 'XIX secolo', 3),
('Ciotola celadon coreana', 'Ceramica', 'XII secolo', 3),
('Piatto in porcellana Ming', 'Ceramica', 'XVI secolo', 3),
('Sigillo in giada imperiale', 'Manufatto ufficiale', 'XVII secolo', 3),
('Scultura lignea di Bodhisattva', 'Scultura', 'XIII secolo', 3),
('Pergamena giapponese emakimono', 'Manoscritto illustrato', 'XV secolo', 3),
('Maschera Bhairava nepalese', 'Maschera', 'XVIII secolo', 3),
('Dipinto thangka tibetano', 'Pittura su tessuto', 'XVII secolo', 3),
('Ciotola cerimoniale giapponese chawan', 'Ceramica', 'XVII secolo', 3),
('Incensiere in bronzo cinese', 'Oggetto rituale', 'XV secolo', 3),
('Statua di Ganesha', 'Scultura', 'XIX secolo', 3),
('Pugnale kris indonesiano', 'Arma tradizionale', 'XVIII secolo', 3),
('Tamburo giapponese taiko', 'Strumento musicale', 'XIX secolo', 3),
('Coppa da tè coreana Joseon', 'Ceramica', 'XV secolo', 3),
('Vaso cloisonné cinese', 'Oggetto decorativo', 'XIX secolo', 3),
('Statuetta di Shiva danzante', 'Scultura', 'XVII secolo', 3),
('Scatola laccata giapponese', 'Oggetto decorativo', 'XVIII secolo', 3),
('Lanterna di pietra giapponese tōrō', 'Arredo artistico', 'XVII secolo', 3),
('Tavoletta votiva ema', 'Oggetto rituale', 'XVIII secolo', 3),
('Tessuto batik giavanese', 'Tessuto artistico', 'XIX secolo', 3),
('Elmo mongolo in ferro', 'Arma tradizionale', 'XIV secolo', 3),
('Scultura in terracotta di guardiano celeste', 'Scultura', 'VIII secolo', 3),
('Dipinto su seta con dragone', 'Pittura', 'XV secolo', 3),
('Specchio di bronzo Han', 'Oggetto rituale', 'I secolo a.C.', 3),
('Cintura ornamentale moghul', 'Gioiello', 'XVII secolo', 3),
('Maschera rituale balinese', 'Maschera', 'XIX secolo', 3),
('Miniatura persiana', 'Pittura miniata', 'XVI secolo', 3),
('Coppa in giada scolpita', 'Oggetto decorativo', 'XVII secolo', 3),
('Stampa di Hiroshige', 'Stampa', 'XIX secolo', 3),
('Idolo votivo indiano in bronzo', 'Scultura', 'XI secolo', 3),
('Armatura samurai yoroi', 'Arma tradizionale', 'XVII secolo', 3),
('Lanterna cinese in carta dipinta', 'Oggetto decorativo', 'XIX secolo', 3),
('Talismano in turchese tibetano', 'Oggetto rituale', 'XVIII secolo', 3),
('Vaso funerario cinese Tang', 'Ceramica', 'VIII secolo', 3),
('Scultura del Buddha Maitreya', 'Scultura', 'X secolo', 3),
('Dipinto su seta di paesaggio Song', 'Pittura', 'XII secolo', 3),

-- GAM - Galleria Civica d’Arte Moderna (id_museo = 4) ~49 rows
('Composizione astratta di Casorati', 'Dipinto', 'XX secolo', 4),
('Scultura in bronzo di Mastroianni', 'Scultura', 'XX secolo', 4),
('Autoritratto futurista', 'Dipinto', 'XX secolo', 4),
('Paesaggio piemontese', 'Dipinto', 'XIX secolo', 4),
('Natura morta con fiori', 'Dipinto', 'XX secolo', 4),
('Opera informale di Burri', 'Dipinto', 'XX secolo', 4),
('Scultura in legno contemporanea', 'Scultura', 'XXI secolo', 4),
('Disegno di De Chirico', 'Disegno', 'XX secolo', 4),
('Composizione cubista', 'Dipinto', 'XX secolo', 4),
('Ritratto di donna', 'Dipinto', 'XIX secolo', 4),
('Scultura in marmo di Medardo Rosso', 'Scultura', 'XIX secolo', 4),
('Paesaggio urbano di Sironi', 'Dipinto', 'XX secolo', 4),
('Bozzetto per scenografia teatrale', 'Disegno', 'XX secolo', 4),
('Trittico astratto', 'Dipinto', 'XX secolo', 4),
('Scultura cinetica', 'Scultura', 'XX secolo', 4),
('Collage surrealista', 'Tecnica mista', 'XX secolo', 4),
('Composizione geometrica minimalista', 'Dipinto', 'XX secolo', 4),
('Installazione luminosa', 'Installazione', 'XXI secolo', 4),
('Ritratto di famiglia borghese', 'Dipinto', 'XIX secolo', 4),
('Opera pop di Rotella', 'Tecnica mista', 'XX secolo', 4),
('Paesaggio con figure', 'Dipinto', 'XIX secolo', 4),
('Scultura in ferro di Consagra', 'Scultura', 'XX secolo', 4),
('Bozzetto di Balla', 'Disegno', 'XX secolo', 4),
('Natura morta futurista', 'Dipinto', 'XX secolo', 4),
('Composizione monocroma', 'Dipinto', 'XX secolo', 4),
('Scultura modulare', 'Scultura', 'XX secolo', 4),
('Opera concettuale su tela', 'Dipinto', 'XX secolo', 4),
('Paesaggio marino impressionista', 'Dipinto', 'XIX secolo', 4),
('Studio di figura femminile', 'Disegno', 'XIX secolo', 4),
('Opera materica di Fontana', 'Dipinto', 'XX secolo', 4),
('Composizione dinamica futurista', 'Dipinto', 'XX secolo', 4),
('Scultura in gesso', 'Scultura', 'XX secolo', 4),
('Tavola astratta di Afro Basaldella', 'Dipinto', 'XX secolo', 4),
('Bozzetto preparatorio di Carrà', 'Disegno', 'XX secolo', 4),
('Installazione multimediale contemporanea', 'Installazione', 'XXI secolo', 4),
('Composizione su vetro', 'Tecnica mista', 'XX secolo', 4),
('Scultura in pietra contemporanea', 'Scultura', 'XXI secolo', 4),
('Ritratto simbolista', 'Dipinto', 'XIX secolo', 4),
('Opera astratta di Melotti', 'Dipinto', 'XX secolo', 4),
('Scultura in acciaio corten', 'Scultura', 'XX secolo', 4),
('Paesaggio alpino piemontese', 'Dipinto', 'XIX secolo', 4),
('Composizione di luce e colore', 'Dipinto', 'XX secolo', 4),
('Opera performativa documentata', 'Installazione', 'XXI secolo', 4),
('Rilievo in ceramica smaltata', 'Scultura', 'XX secolo', 4),
('Disegno preparatorio per murale', 'Disegno', 'XX secolo', 4),
('Paesaggio astratto di Tancredi', 'Dipinto', 'XX secolo', 4),
('Opera di arte povera con materiali naturali', 'Installazione', 'XX secolo', 4),
('Scultura di Arnaldo Pomodoro', 'Scultura', 'XX secolo', 4),
('Composizione informale su tela', 'Dipinto', 'XX secolo', 4),
('Opera digitale interattiva', 'Installazione', 'XXI secolo', 4),

-- Museo dell’Automobile (id_museo = 5) ~50 rows
('Fiat 3½ HP', 'Automobile', 'XIX secolo', 5),
('Fiat Zero', 'Automobile', 'XX secolo', 5),
('Lancia Lambda', 'Automobile', 'XX secolo', 5),
('Ferrari 250 GTO', 'Automobile', 'XX secolo', 5),
('Fiat Panda prima serie', 'Automobile', 'XX secolo', 5),
('Prototipo elettrico Fiat Panda Elettra', 'Automobile', 'XX secolo', 5),
('Volante in legno Balilla', 'Componente automobilistico', 'XX secolo', 5),
('Motore di Formula 1 Ferrari', 'Motore', 'XX secolo', 5),
('Alfa Romeo 6C 1750', 'Automobile', 'XX secolo', 5),
('Lancia Stratos HF', 'Automobile', 'XX secolo', 5),
('Fiat Topolino', 'Automobile', 'XX secolo', 5),
('Ferrari Testarossa', 'Automobile', 'XX secolo', 5),
('Prototipo Pininfarina Modulo', 'Automobile', 'XX secolo', 5),
('Fiat 500', 'Automobile', 'XX secolo', 5),
('Motore Fiat 124 Spider', 'Motore', 'XX secolo', 5),
('Alfa Romeo Giulia Sprint GTA', 'Automobile', 'XX secolo', 5),
('Lancia Delta Integrale', 'Automobile', 'XX secolo', 5),
('Fiat 8V Supersonic', 'Automobile', 'XX secolo', 5),
('Volante Ferrari F40', 'Componente automobilistico', 'XX secolo', 5),
('Prototipo Lancia Sibilo', 'Automobile', 'XX secolo', 5),
('Fiat Multipla 600', 'Automobile', 'XX secolo', 5),
('Targa Mille Miglia', 'Premio automobilistico', 'XX secolo', 5),
('Motore Alfa Romeo V6 Busso', 'Motore', 'XX secolo', 5),
('Fiat 131 Abarth Rally', 'Automobile', 'XX secolo', 5),
('Ferrari 312T', 'Automobile da corsa', 'XX secolo', 5),
('Poster pubblicitario Lancia Aurelia', 'Poster', 'XX secolo', 5),
('Tuta da corsa di Niki Lauda', 'Abbigliamento sportivo', 'XX secolo', 5),
('Volante di Gilles Villeneuve', 'Componente automobilistico', 'XX secolo', 5),
('Casco di Michael Schumacher', 'Abbigliamento sportivo', 'XXI secolo', 5),
('Pneumatico da gara Pirelli', 'Componente automobilistico', 'XXI secolo', 5),
('Prototipo elettrico Fiat Concept Centoventi', 'Automobile', 'XXI secolo', 5),
('Alfa Romeo 33 Stradale', 'Automobile', 'XX secolo', 5),
('Ferrari LaFerrari', 'Automobile', 'XXI secolo', 5),
('Fiat Turbina', 'Automobile sperimentale', 'XX secolo', 5),
('Fiat Campagnola', 'Automobile', 'XX secolo', 5),
('Motore Lancia Appia', 'Motore', 'XX secolo', 5),
('Volante in pelle Ferrari 512 BB', 'Componente automobilistico', 'XX secolo', 5),
('Fiat Uno Turbo i.e.', 'Automobile', 'XX secolo', 5),
('Lancia Fulvia Coupé', 'Automobile', 'XX secolo', 5),
('Prototipo Alfa Romeo BAT 5', 'Automobile', 'XX secolo', 5),
('Fiat Ritmo Cabriolet', 'Automobile', 'XX secolo', 5),
('Ferrari F1-2000', 'Automobile da corsa', 'XXI secolo', 5),
('Motore Ferrari V12', 'Motore', 'XX secolo', 5),
('Poster “La Fiat a Torino”', 'Poster', 'XX secolo', 5),
('Casco di Gilles Villeneuve', 'Abbigliamento sportivo', 'XX secolo', 5),
('Fiat 1100 Musone', 'Automobile', 'XX secolo', 5),
('Prototipo Lancia Stratos Zero', 'Automobile', 'XX secolo', 5),
('Motore da competizione Maserati 250F', 'Motore', 'XX secolo', 5),
('Volante Lancia Thema 8.32', 'Componente automobilistico', 'XX secolo', 5),
('Fiat Cinquecento Sporting', 'Automobile', 'XX secolo', 5),
('Targa celebrativa Museo dell’Automobile', 'Oggetto commemorativo', 'XXI secolo', 5),

-- Museo del Risorgimento (id_museo = 6) ~50 rows
('Uniforme di Cavour', 'Abbigliamento storico', 'XIX secolo', 6),
('Statuto Albertino originale', 'Documento', 'XIX secolo', 6),
('Spada di Garibaldi', 'Arma storica', 'XIX secolo', 6),
('Bandiera del Regno di Sardegna', 'Reperto storico', 'XIX secolo', 6),
('Lettera autografa di Mazzini', 'Documento', 'XIX secolo', 6),
('Medaglia commemorativa dell’Unità d’Italia', 'Oggetto commemorativo', 'XIX secolo', 6),
('Divisa da bersagliere', 'Abbigliamento militare', 'XIX secolo', 6),
('Mappa delle battaglie di Novara', 'Documento', 'XIX secolo', 6),
('Fucile modello 1844', 'Arma storica', 'XIX secolo', 6),
('Sciabola di Vittorio Emanuele II', 'Arma storica', 'XIX secolo', 6),
('Ritratto di Camillo Benso di Cavour', 'Dipinto', 'XIX secolo', 6),
('Copricapo da ussaro', 'Abbigliamento militare', 'XIX secolo', 6),
('Tamburo da campo piemontese', 'Strumento militare', 'XIX secolo', 6),
('Proclama di Garibaldi', 'Documento', 'XIX secolo', 6),
('Bandiera dei Mille', 'Reperto storico', 'XIX secolo', 6),
('Uniforme di ufficiale sabaudo', 'Abbigliamento militare', 'XIX secolo', 6),
('Medaglia di Crimea', 'Decorazione militare', 'XIX secolo', 6),
('Carta geografica del Regno d’Italia', 'Documento', 'XIX secolo', 6),
('Bicorno di Cavour', 'Abbigliamento storico', 'XIX secolo', 6),
('Fucile a pietra focaia', 'Arma storica', 'XVIII secolo', 6),
('Sigillo del Parlamento Subalpino', 'Oggetto istituzionale', 'XIX secolo', 6),
('Bandiera del Primo Reggimento Alpini', 'Reperto storico', 'XIX secolo', 6),
('Lettera di Giuseppe Garibaldi a Nizza', 'Documento', 'XIX secolo', 6),
('Tromba da battaglia', 'Strumento militare', 'XIX secolo', 6),
('Medaglia d’argento al valor militare', 'Decorazione militare', 'XIX secolo', 6),
('Ritratto di Giuseppe Mazzini', 'Dipinto', 'XIX secolo', 6),
('Spilla patriottica tricolore', 'Oggetto commemorativo', 'XIX secolo', 6),
('Pistola a colpo singolo', 'Arma storica', 'XIX secolo', 6),
('Uniforme garibaldina', 'Abbigliamento militare', 'XIX secolo', 6),
('Stendardo sabaudo', 'Reperto storico', 'XIX secolo', 6),
('Copricapo da carabiniere', 'Abbigliamento militare', 'XIX secolo', 6),
('Medaglia per la Campagna del 1860', 'Decorazione militare', 'XIX secolo', 6),
('Documento di annessione del Veneto', 'Documento', 'XIX secolo', 6),
('Ritratto di Vittorio Emanuele II', 'Dipinto', 'XIX secolo', 6),
('Sciarpa tricolore patriottica', 'Abbigliamento storico', 'XIX secolo', 6),
('Canne da fucile a retrocarica', 'Arma storica', 'XIX secolo', 6),
('Bandiere delle truppe piemontesi', 'Reperto storico', 'XIX secolo', 6),
('Manoscritto di proclama unitario', 'Documento', 'XIX secolo', 6),
('Sigillo del Regno d’Italia', 'Oggetto istituzionale', 'XIX secolo', 6),
('Elmo da cavalleria sabauda', 'Abbigliamento militare', 'XIX secolo', 6),
('Uniforme di generale garibaldino', 'Abbigliamento militare', 'XIX secolo', 6),
('Medaglia per la battaglia di San Martino', 'Decorazione militare', 'XIX secolo', 6),
('Proclama di Vittorio Emanuele II', 'Documento', 'XIX secolo', 6),
('Ritratto di Giuseppe Garibaldi', 'Dipinto', 'XIX secolo', 6),
('Spada di ufficiale piemontese', 'Arma storica', 'XIX secolo', 6),
('Bandiera del plebiscito toscano', 'Reperto storico', 'XIX secolo', 6),
('Tavoletta commemorativa dell’Unità', 'Oggetto commemorativo', 'XIX secolo', 6),
('Lettera di Cavour al Re', 'Documento', 'XIX secolo', 6),
('Tamburo da parata', 'Strumento militare', 'XIX secolo', 6),
('Medaglia d’oro al valor civile', 'Decorazione militare', 'XIX secolo', 6),
('Mappa delle battaglie del Risorgimento', 'Documento', 'XIX secolo', 6),

-- Palazzo Madama (id_museo = 7) ~50 rows
('Vetrata gotica', 'Opera decorativa', 'XIV secolo', 7),
('Trono ducale', 'Arredo', 'XVII secolo', 7),
('Dipinto di Carlo Emanuele II', 'Dipinto', 'XVII secolo', 7),
('Arazzo fiammingo', 'Tessuto', 'XVI secolo', 7),
('Coppa rinascimentale in argento', 'Oggetto decorativo', 'XVI secolo', 7),
('Cassettone piemontese', 'Arredo', 'XVIII secolo', 7),
('Miniatura su pergamena', 'Miniatura', 'XV secolo', 7),
('Pala d’altare barocca', 'Dipinto', 'XVII secolo', 7),
('Specchiera dorata rococò', 'Arredo', 'XVIII secolo', 7),
('Croce processionale in argento', 'Oggetto liturgico', 'XV secolo', 7),
('Cofanetto in avorio scolpito', 'Oggetto decorativo', 'XIV secolo', 7),
('Vaso in maiolica di Deruta', 'Ceramica', 'XVI secolo', 7),
('Ritratto nobiliare piemontese', 'Dipinto', 'XVIII secolo', 7),
('Tavola lignea con Madonna col Bambino', 'Dipinto', 'XV secolo', 7),
('Orologio da tavolo barocco', 'Oggetto decorativo', 'XVII secolo', 7),
('Statuetta lignea policroma', 'Scultura', 'XIV secolo', 7),
('Tessuto damascato veneziano', 'Tessuto', 'XVI secolo', 7),
('Candelabro in bronzo dorato', 'Oggetto decorativo', 'XVII secolo', 7),
('Piatto in maiolica istoriata', 'Ceramica', 'XVI secolo', 7),
('Cornice dorata barocca', 'Arredo', 'XVII secolo', 7),
('Manoscritto miniato liturgico', 'Manoscritto', 'XV secolo', 7),
('Cassapanca intagliata', 'Arredo', 'XVI secolo', 7),
('Coppa in cristallo di rocca', 'Oggetto decorativo', 'XVII secolo', 7),
('Altare ligneo scolpito', 'Arredo religioso', 'XV secolo', 7),
('Rilievo in marmo con angeli', 'Scultura', 'XVI secolo', 7),
('Pendente smaltato rinascimentale', 'Gioiello', 'XVI secolo', 7),
('Tarsia lignea prospettica', 'Opera decorativa', 'XV secolo', 7),
('Brocca in rame cesellato', 'Oggetto d’uso', 'XVII secolo', 7),
('Vetrata con stemma sabaudo', 'Opera decorativa', 'XV secolo', 7),
('Arazzo con scene bibliche', 'Tessuto', 'XVI secolo', 7),
('Scultura marmorea di santo', 'Scultura', 'XV secolo', 7),
('Cornice con doratura originale', 'Arredo', 'XVIII secolo', 7),
('Calice liturgico in argento', 'Oggetto liturgico', 'XVI secolo', 7),
('Cassettone intarsiato ligure', 'Arredo', 'XVII secolo', 7),
('Dipinto di scuola fiamminga', 'Dipinto', 'XVI secolo', 7),
('Vaso da farmacia in maiolica', 'Ceramica', 'XV secolo', 7),
('Cofanetto intarsiato in madreperla', 'Oggetto decorativo', 'XVII secolo', 7),
('Croce astile gotica', 'Oggetto liturgico', 'XIV secolo', 7),
('Ritratto di nobildonna sabauda', 'Dipinto', 'XVIII secolo', 7),
('Pala d’altare di scuola piemontese', 'Dipinto', 'XVII secolo', 7),
('Baldacchino ricamato', 'Tessuto', 'XVII secolo', 7),
('Statuetta di San Michele Arcangelo', 'Scultura', 'XV secolo', 7),
('Cassone nuziale decorato', 'Arredo', 'XVI secolo', 7),
('Vaso in vetro veneziano soffiato', 'Oggetto decorativo', 'XVI secolo', 7),
('Candelabro in ferro battuto', 'Oggetto d’uso', 'XV secolo', 7),
('Arazzo con stemma nobiliare', 'Tessuto', 'XVII secolo', 7),
('Rilievo in terracotta invetriata', 'Scultura', 'XV secolo', 7),
('Specchio barocco piemontese', 'Arredo', 'XVIII secolo', 7),
('Dipinto di Madonna con Bambino', 'Dipinto', 'XV secolo', 7),
('Cofanetto rinascimentale in legno dorato', 'Oggetto decorativo', 'XVI secolo', 7),
('Lampadario in bronzo cesellato', 'Arredo', 'XVII secolo', 7),

-- Museo della Montagna (id_museo = 8) ~50 rows
('Piccozza di Duca degli Abruzzi', 'Attrezzo alpinistico', 'XX secolo', 8),
('Cartina del K2', 'Documento', 'XX secolo', 8),
('Scarponi da alpinismo', 'Oggetto sportivo', 'XX secolo', 8),
('Tenda da spedizione himalayana', 'Oggetto sportivo', 'XX secolo', 8),
('Macchina fotografica Leica alpinistica', 'Strumento fotografico', 'XX secolo', 8),
('Ghiacciaio in miniatura didattico', 'Modello scientifico', 'XX secolo', 8),
('Zaino in tela e cuoio', 'Oggetto sportivo', 'XX secolo', 8),
('Corda di canapa da scalata', 'Attrezzo alpinistico', 'XX secolo', 8),
('Chiodo da ghiaccio', 'Attrezzo alpinistico', 'XX secolo', 8),
('Lampada a carburo da rifugio', 'Oggetto d’uso', 'XX secolo', 8),
('Diario di spedizione sul Monte Bianco', 'Documento', 'XX secolo', 8),
('Fotografia della prima salita al Cervino', 'Fotografia storica', 'XIX secolo', 8),
('Sci di legno con attacchi originali', 'Oggetto sportivo', 'XX secolo', 8),
('Piolet da ghiaccio', 'Attrezzo alpinistico', 'XX secolo', 8),
('Tuta da spedizione in piumino', 'Abbigliamento tecnico', 'XX secolo', 8),
('Maschera da ossigeno per alta quota', 'Oggetto tecnico', 'XX secolo', 8),
('Altimetro aneroide', 'Strumento scientifico', 'XX secolo', 8),
('Cramponi d’acciaio', 'Attrezzo alpinistico', 'XX secolo', 8),
('Giacca in lana da montagna', 'Abbigliamento', 'XX secolo', 8),
('Mappa topografica delle Alpi', 'Documento', 'XX secolo', 8),
('Ritratto del Duca degli Abruzzi', 'Dipinto', 'XX secolo', 8),
('Binocolo da osservazione alpina', 'Strumento ottico', 'XX secolo', 8),
('Guanti in pelle per scalata', 'Abbigliamento', 'XX secolo', 8),
('Bastone da escursionismo', 'Attrezzo alpinistico', 'XX secolo', 8),
('Cartolina della Capanna Margherita', 'Documento', 'XX secolo', 8),
('Racchette da neve in vimini', 'Oggetto sportivo', 'XX secolo', 8),
('Macchina da scrivere per diari di spedizione', 'Strumento d’uso', 'XX secolo', 8),
('Lampada frontale con batteria', 'Oggetto tecnico', 'XX secolo', 8),
('Ritratto fotografico di Walter Bonatti', 'Fotografia', 'XX secolo', 8),
('Libretto del Club Alpino Italiano', 'Documento', 'XX secolo', 8),
('Modello in scala del Monte Rosa', 'Modello scientifico', 'XX secolo', 8),
('Tenda in tessuto cerato', 'Oggetto sportivo', 'XX secolo', 8),
('Ascia da ghiaccio antica', 'Attrezzo alpinistico', 'XIX secolo', 8),
('Cartina geologica delle Alpi occidentali', 'Documento', 'XX secolo', 8),
('Zaino in pelle con attrezzatura originale', 'Oggetto sportivo', 'XX secolo', 8),
('Cassetta di pronto soccorso da spedizione', 'Oggetto tecnico', 'XX secolo', 8),
('Scarponi da sci con lacci', 'Oggetto sportivo', 'XX secolo', 8),
('Anemometro portatile', 'Strumento scientifico', 'XX secolo', 8),
('Borraccia in alluminio', 'Oggetto d’uso', 'XX secolo', 8),
('Taccuino di viaggio alpino', 'Documento', 'XX secolo', 8),
('Fotografia della vetta del K2', 'Fotografia storica', 'XX secolo', 8),
('Sciarpa del Club Alpino Italiano', 'Abbigliamento', 'XX secolo', 8),
('Bussole da montagna', 'Strumento scientifico', 'XX secolo', 8),
('Filmato della spedizione Karakorum', 'Pellicola', 'XX secolo', 8),
('Guida alpina autografata', 'Documento', 'XX secolo', 8),
('Giacca a vento da alta quota', 'Abbigliamento tecnico', 'XX secolo', 8),
('Casco da arrampicata', 'Oggetto sportivo', 'XX secolo', 8),
('Lampada solare da bivacco', 'Oggetto tecnico', 'XXI secolo', 8),
('Cartina della catena del Karakorum', 'Documento', 'XX secolo', 8),
('Pantaloni da scalata in lana', 'Abbigliamento', 'XX secolo', 8),
('Bastoncini da sci', 'Oggetto sportivo', 'XX secolo', 8),

-- Museo Pietro Micca (id_museo = 9) ~50 rows
('Uniforme da artigliere', 'Abbigliamento militare', 'XVIII secolo', 9),
('Mappa dell’assedio di Torino', 'Documento', 'XVIII secolo', 9),
('Cannone in bronzo', 'Arma', 'XVIII secolo', 9),
('Spada sabauda', 'Arma', 'XVIII secolo', 9),
('Tamburo da battaglia', 'Oggetto militare', 'XVIII secolo', 9),
('Bandiera piemontese', 'Reperto storico', 'XVIII secolo', 9),
('Elmo da granatiere', 'Abbigliamento militare', 'XVIII secolo', 9),
('Pistola a pietra focaia', 'Arma', 'XVIII secolo', 9),
('Baionetta da fucile', 'Arma', 'XVIII secolo', 9),
('Mappa delle gallerie sotterranee', 'Documento', 'XVIII secolo', 9),
('Uniforme da ufficiale sabaudo', 'Abbigliamento militare', 'XVIII secolo', 9),
('Modello del bastione San Maurizio', 'Modello architettonico', 'XX secolo', 9),
('Ritratto di Pietro Micca', 'Dipinto', 'XVIII secolo', 9),
('Chiave originale della cittadella di Torino', 'Oggetto storico', 'XVIII secolo', 9),
('Granata a mano francese', 'Arma', 'XVIII secolo', 9),
('Lettera del comandante Thaon di Revel', 'Documento', 'XVIII secolo', 9),
('Tamburo di marcia', 'Oggetto militare', 'XVIII secolo', 9),
('Cartina strategica delle fortificazioni', 'Documento', 'XVIII secolo', 9),
('Giubba militare sabauda', 'Abbigliamento militare', 'XVIII secolo', 9),
('Sciabola di cavalleria', 'Arma', 'XVIII secolo', 9),
('Fucile a miccia', 'Arma', 'XVII secolo', 9),
('Stendardo dei difensori di Torino', 'Reperto storico', 'XVIII secolo', 9),
('Ritratto del Duca di Savoia Vittorio Amedeo II', 'Dipinto', 'XVIII secolo', 9),
('Documento di resa delle truppe francesi', 'Documento', 'XVIII secolo', 9),
('Cartucciera in cuoio', 'Oggetto militare', 'XVIII secolo', 9),
('Elmo francese con decorazioni', 'Abbigliamento militare', 'XVIII secolo', 9),
('Mappa tattica della cittadella', 'Documento', 'XVIII secolo', 9),
('Sciarpa del corpo degli artiglieri', 'Abbigliamento militare', 'XVIII secolo', 9),
('Lampada ad olio da galleria', 'Oggetto d’uso', 'XVIII secolo', 9),
('Tavola illustrata delle fortificazioni', 'Documento', 'XVIII secolo', 9),
('Tamburo da segnale', 'Oggetto militare', 'XVIII secolo', 9),
('Pugnale da trincea', 'Arma', 'XVIII secolo', 9),
('Medaglia commemorativa della difesa di Torino', 'Oggetto commemorativo', 'XVIII secolo', 9),
('Bicorno sabaudo', 'Abbigliamento militare', 'XVIII secolo', 9),
('Divisa da granatiere piemontese', 'Abbigliamento militare', 'XVIII secolo', 9),
('Canne da fucile originali', 'Arma', 'XVIII secolo', 9),
('Pergamena con planimetria delle gallerie', 'Documento', 'XVIII secolo', 9),
('Scudo sabaudo in ferro', 'Arma difensiva', 'XVIII secolo', 9),
('Fischietto di comando', 'Oggetto militare', 'XVIII secolo', 9),
('Proiettile di cannone', 'Reperto bellico', 'XVIII secolo', 9),
('Modello tridimensionale della cittadella', 'Modello architettonico', 'XX secolo', 9),
('Torcia da galleria', 'Oggetto d’uso', 'XVIII secolo', 9),
('Documento di nomina di Pietro Micca', 'Documento', 'XVIII secolo', 9),
('Ritratto di un ufficiale sabaudo', 'Dipinto', 'XVIII secolo', 9),
('Fucile da muro', 'Arma', 'XVIII secolo', 9),
('Bandiera di compagnia sabauda', 'Reperto storico', 'XVIII secolo', 9),
('Tavola illustrata dell’assedio di Torino', 'Documento', 'XVIII secolo', 9),
('Medaglia al valore per la difesa di Torino', 'Oggetto commemorativo', 'XVIII secolo', 9),
('Cintura da ufficiale', 'Abbigliamento militare', 'XVIII secolo', 9),
('Moschetto da fanteria', 'Arma', 'XVIII secolo', 9),
('Modello della galleria di contromina', 'Modello architettonico', 'XX secolo', 9),

-- Museo di Anatomia Umana (id_museo = 10) ~50 rows
('Scheletro umano completo', 'Preparato anatomico', 'XIX secolo', 10),
('Modello cerebrale in cera', 'Modello scientifico', 'XIX secolo', 10),
('Cuore sezionato', 'Preparato anatomico', 'XIX secolo', 10),
('Scheletro fetale', 'Preparato anatomico', 'XIX secolo', 10),
('Apparato scheletrico comparato', 'Preparato anatomico', 'XX secolo', 10),
('Modello muscolare in cera', 'Modello scientifico', 'XIX secolo', 10),
('Teschio umano con craniosinostosi', 'Preparato anatomico', 'XIX secolo', 10),
('Collezione di crani etnografici', 'Preparato antropologico', 'XIX secolo', 10),
('Preparato di cervello umano sezionato', 'Preparato anatomico', 'XIX secolo', 10),
('Modello di occhio in gesso dipinto', 'Modello scientifico', 'XIX secolo', 10),
('Scheletro di primate', 'Preparato comparato', 'XIX secolo', 10),
('Preparato di arto superiore con muscoli', 'Preparato anatomico', 'XIX secolo', 10),
('Tavola anatomica litografata', 'Documento scientifico', 'XIX secolo', 10),
('Cranio con dentatura patologica', 'Preparato anatomico', 'XIX secolo', 10),
('Modello dell’orecchio interno', 'Modello scientifico', 'XX secolo', 10),
('Cervello in cera con sezioni', 'Modello scientifico', 'XIX secolo', 10),
('Preparato di arto inferiore', 'Preparato anatomico', 'XIX secolo', 10),
('Vetrina con preparati di organi interni', 'Esposizione anatomica', 'XIX secolo', 10),
('Collezione di vertebre umane', 'Preparato anatomico', 'XIX secolo', 10),
('Modello di apparato digerente', 'Modello scientifico', 'XIX secolo', 10),
('Scheletro di neonato', 'Preparato anatomico', 'XIX secolo', 10),
('Preparato di fegato umano', 'Preparato anatomico', 'XIX secolo', 10),
('Modello in cera dell’apparato circolatorio', 'Modello scientifico', 'XIX secolo', 10),
('Teschio trepanato', 'Preparato anatomico', 'XIX secolo', 10),
('Serie di cervelli umani patologici', 'Preparato anatomico', 'XIX secolo', 10),
('Cervello di feto in formalina', 'Preparato anatomico', 'XIX secolo', 10),
('Modello dell’apparato respiratorio', 'Modello scientifico', 'XX secolo', 10),
('Scheletro parziale con deformazioni ossee', 'Preparato anatomico', 'XIX secolo', 10),
('Preparato di arto amputato', 'Preparato anatomico', 'XIX secolo', 10),
('Cranio microcefalo', 'Preparato anatomico', 'XIX secolo', 10),
('Cervello cerebellare sezionato', 'Preparato anatomico', 'XIX secolo', 10),
('Modello di sistema nervoso periferico', 'Modello scientifico', 'XIX secolo', 10),
('Preparato di midollo spinale', 'Preparato anatomico', 'XIX secolo', 10),
('Cranio con protesi dentaria antica', 'Preparato anatomico', 'XIX secolo', 10),
('Serie di ossa lunghe umane', 'Preparato anatomico', 'XIX secolo', 10),
('Modello dell’apparato urogenitale maschile', 'Modello scientifico', 'XIX secolo', 10),
('Cervello cerebrale sezionato trasversalmente', 'Preparato anatomico', 'XIX secolo', 10),
('Preparato di polmoni con tubercolosi', 'Preparato anatomico', 'XIX secolo', 10),
('Scheletro di cane per confronto anatomico', 'Preparato comparato', 'XIX secolo', 10),
('Modello del cuore in sezione', 'Modello scientifico', 'XIX secolo', 10),
('Tavola anatomica di Luigi Rolando', 'Documento scientifico', 'XIX secolo', 10),
('Preparato di encefalo in formalina', 'Preparato anatomico', 'XIX secolo', 10),
('Cranio di individuo anziano', 'Preparato anatomico', 'XIX secolo', 10),
('Scheletro parziale infantile', 'Preparato anatomico', 'XIX secolo', 10),
('Modello dell’apparato linfatico', 'Modello scientifico', 'XIX secolo', 10),
('Preparato di cervello con emorragia', 'Preparato anatomico', 'XIX secolo', 10),
('Collezione di preparati vascolari', 'Preparato anatomico', 'XIX secolo', 10),
('Scheletro femminile completo', 'Preparato anatomico', 'XIX secolo', 10),
('Modello anatomico di busto umano', 'Modello scientifico', 'XX secolo', 10),
('Preparato del sistema venoso', 'Preparato anatomico', 'XIX secolo', 10),
('Modello di scheletro articolato', 'Modello scientifico', 'XIX secolo', 10),

-- Museo Lombroso (id_museo = 11) ~50 rows
('Teschio di brigante', 'Reperto antropologico', 'XIX secolo', 11),
('Strumenti cranici', 'Strumento scientifico', 'XIX secolo', 11),
('Taccuino di Cesare Lombroso', 'Documento', 'XIX secolo', 11),
('Campione di cervello criminale', 'Preparato anatomico', 'XIX secolo', 11),
('Microscopio antropologico', 'Strumento scientifico', 'XIX secolo', 11),
('Scheda antropometrica', 'Documento', 'XIX secolo', 11),
('Fotografia di detenuto', 'Fotografia storica', 'XIX secolo', 11),
('Calco cranico in gesso', 'Reperto antropologico', 'XIX secolo', 11),
('Cranio con anomalie morfologiche', 'Reperto antropologico', 'XIX secolo', 11),
('Tavola illustrata di fisiognomica', 'Documento scientifico', 'XIX secolo', 11),
('Misuratore cranico in metallo', 'Strumento scientifico', 'XIX secolo', 11),
('Manoscritto di appunti di Lombroso', 'Documento', 'XIX secolo', 11),
('Maschera mortuaria di criminale', 'Reperto antropologico', 'XIX secolo', 11),
('Calibro antropometrico', 'Strumento scientifico', 'XIX secolo', 11),
('Cervello sezionato di condannato', 'Preparato anatomico', 'XIX secolo', 11),
('Disegno di fisionomie criminali', 'Documento illustrato', 'XIX secolo', 11),
('Fotografia di Cesare Lombroso', 'Fotografia storica', 'XIX secolo', 11),
('Ritratto di Cesare Lombroso', 'Dipinto', 'XIX secolo', 11),
('Cranio con segni di trauma', 'Reperto antropologico', 'XIX secolo', 11),
('Strumento per misurare il naso', 'Strumento scientifico', 'XIX secolo', 11),
('Scheda antropologica di prigioniero', 'Documento', 'XIX secolo', 11),
('Cranio di donna criminale', 'Reperto antropologico', 'XIX secolo', 11),
('Tavola litografica di tipologie criminali', 'Documento scientifico', 'XIX secolo', 11),
('Collezione di cervelli umani', 'Preparato anatomico', 'XIX secolo', 11),
('Maschera in cera di detenuto', 'Reperto antropologico', 'XIX secolo', 11),
('Microscopio ottico da laboratorio', 'Strumento scientifico', 'XIX secolo', 11),
('Calco facciale in gesso', 'Reperto antropologico', 'XIX secolo', 11),
('Libretto “L’uomo delinquente”', 'Documento', 'XIX secolo', 11),
('Cranio con caratteristiche ataviche', 'Reperto antropologico', 'XIX secolo', 11),
('Scheda segnaletica carceraria', 'Documento', 'XIX secolo', 11),
('Misuratore di angoli facciali', 'Strumento scientifico', 'XIX secolo', 11),
('Preparato cerebrale patologico', 'Preparato anatomico', 'XIX secolo', 11),
('Apparecchio fotografico da laboratorio', 'Strumento scientifico', 'XIX secolo', 11),
('Serie di fotografie segnaletiche', 'Fotografia storica', 'XIX secolo', 11),
('Tavola comparativa di crani', 'Documento scientifico', 'XIX secolo', 11),
('Cranio con protesi dentaria', 'Reperto antropologico', 'XIX secolo', 11),
('Cervello di epilettico', 'Preparato anatomico', 'XIX secolo', 11),
('Maschera mortuaria in gesso', 'Reperto antropologico', 'XIX secolo', 11),
('Strumento per misurare la mandibola', 'Strumento scientifico', 'XIX secolo', 11),
('Scheda di laboratorio di antropometria', 'Documento', 'XIX secolo', 11),
('Teschio di soldato disertore', 'Reperto antropologico', 'XIX secolo', 11),
('Preparato di cervello femminile', 'Preparato anatomico', 'XIX secolo', 11),
('Fotografia di laboratorio di Lombroso', 'Fotografia storica', 'XIX secolo', 11),
('Cranio con deformazioni craniche', 'Reperto antropologico', 'XIX secolo', 11),
('Tavola antropometrica di confronto', 'Documento scientifico', 'XIX secolo', 11),
('Calco di mano criminale', 'Reperto antropologico', 'XIX secolo', 11),
('Microscopio con incisione “Torino”', 'Strumento scientifico', 'XIX secolo', 11),
('Libretto di appunti di laboratorio', 'Documento', 'XIX secolo', 11),
('Cranio di ladro piemontese', 'Reperto antropologico', 'XIX secolo', 11),
('Maschera in cera di brigante calabrese', 'Reperto antropologico', 'XIX secolo', 11),
('Scheda segnaletica compilata da Lombroso', 'Documento', 'XIX secolo', 11),

-- Museo della Sindone (id_museo = 12) ~50 rows
('Fotografia originale di Secondo Pia', 'Fotografia', 'XIX secolo', 12),
('Cassetta reliquiario', 'Oggetto sacro', 'XVII secolo', 12),
('Riproduzione della Sindone', 'Reperto religioso', 'XVI secolo', 12),
('Vetrina liturgica', 'Arredo sacro', 'XVII secolo', 12),
('Croce processionale', 'Oggetto sacro', 'XVII secolo', 12),
('Manoscritto devozionale', 'Documento religioso', 'XVII secolo', 12),
('Teca per reliquie', 'Oggetto sacro', 'XVII secolo', 12),
('Tela sindonica riproduttiva', 'Reperto religioso', 'XVII secolo', 12),
('Candelabro processionale', 'Oggetto liturgico', 'XVII secolo', 12),
('Calice in argento cesellato', 'Oggetto liturgico', 'XVII secolo', 12),
('Stampa della Sindone di Torino', 'Stampa religiosa', 'XVIII secolo', 12),
('Crocefisso ligneo', 'Oggetto sacro', 'XVII secolo', 12),
('Fotografia a luce negativa della Sindone', 'Fotografia', 'XIX secolo', 12),
('Reliquiario dorato', 'Oggetto sacro', 'XVII secolo', 12),
('Documento della Confraternita del SS. Sudario', 'Documento religioso', 'XVII secolo', 12),
('Custodia in velluto per reliquia', 'Oggetto sacro', 'XVII secolo', 12),
('Miniatura della Sindone', 'Miniatura religiosa', 'XVII secolo', 12),
('Incisione di Gesù Crocifisso', 'Stampa religiosa', 'XVII secolo', 12),
('Medaglia commemorativa della Sindone', 'Oggetto commemorativo', 'XIX secolo', 12),
('Dipinto della Traslazione della Sindone', 'Dipinto', 'XVII secolo', 12),
('Manuale di preghiere', 'Documento religioso', 'XVIII secolo', 12),
('Fotografia del Duomo di Torino post incendio', 'Fotografia', 'XX secolo', 12),
('Rosario in legno d’ulivo', 'Oggetto devozionale', 'XIX secolo', 12),
('Stampa della Cappella del Guarini', 'Stampa artistica', 'XVII secolo', 12),
('Scatola reliquiario in rame dorato', 'Oggetto sacro', 'XVII secolo', 12),
('Pergamena con benedizione papale', 'Documento religioso', 'XVIII secolo', 12),
('Velo liturgico ricamato', 'Tessuto religioso', 'XVII secolo', 12),
('Busto reliquiario di santo', 'Scultura religiosa', 'XVII secolo', 12),
('Riproduzione fotografica della Sindone del 1931', 'Fotografia', 'XX secolo', 12),
('Tavola esplicativa della figura impressa', 'Pannello didattico', 'XX secolo', 12),
('Candeliere in ottone', 'Oggetto liturgico', 'XVII secolo', 12),
('Tovaglia d’altare ricamata', 'Tessuto liturgico', 'XVIII secolo', 12),
('Libretto di preghiere mariane', 'Documento religioso', 'XIX secolo', 12),
('Coperta in seta con croce', 'Tessuto religioso', 'XVIII secolo', 12),
('Scatola di trasporto della Sindone', 'Oggetto storico', 'XVII secolo', 12),
('Disegno a penna della Sindone', 'Disegno religioso', 'XVII secolo', 12),
('Targa commemorativa dell’incendio del 1997', 'Oggetto commemorativo', 'XX secolo', 12),
('Copricapo liturgico', 'Abbigliamento religioso', 'XVIII secolo', 12),
('Lampada votiva', 'Oggetto sacro', 'XVII secolo', 12),
('Libro “Memorie della Santa Sindone”', 'Documento religioso', 'XIX secolo', 12),
('Riproduzione fotografica a colori della Sindone', 'Fotografia', 'XX secolo', 12),
('Vaso liturgico in bronzo', 'Oggetto liturgico', 'XVII secolo', 12),
('Pergamena di concessione pontificia', 'Documento religioso', 'XVIII secolo', 12),
('Icona bizantina del Cristo', 'Icona religiosa', 'XVI secolo', 12),
('Croce pettorale in argento', 'Oggetto liturgico', 'XVII secolo', 12),
('Libro di preghiere della Confraternita', 'Documento religioso', 'XVII secolo', 12),
('Stampa del Volto Santo', 'Stampa religiosa', 'XVII secolo', 12),
('Campanella liturgica', 'Oggetto sacro', 'XVIII secolo', 12),
('Reliquia di tessuto bruciato della Sindone', 'Reperto religioso', 'XX secolo', 12),
('Fotografia della Cappella del Guarini restaurata', 'Fotografia', 'XXI secolo', 12),
('Pannello didattico sul restauro', 'Materiale espositivo', 'XXI secolo', 12),

-- Museo Ferroviario Piemontese (id_museo = 13) ~52 rows
('Locomotiva a vapore Gr. 640', 'Locomotiva', 'XX secolo', 13),
('Carrozza reale', 'Vagone', 'XIX secolo', 13),
('Divisa ferroviaria', 'Abbigliamento storico', 'XX secolo', 13),
('Biglietteria originale', 'Arredo tecnico', 'XX secolo', 13),
('Targa di locomotiva FS', 'Reperto tecnico', 'XX secolo', 13),
('Orologio della stazione di Torino Porta Nuova', 'Strumento meccanico', 'XIX secolo', 13),
('Lanterna ferroviaria', 'Oggetto tecnico', 'XIX secolo', 13),
('Modello in scala di locomotiva Gr. 740', 'Modello tecnico', 'XX secolo', 13),
('Carro merci FS', 'Vagone', 'XX secolo', 13),
('Segnale ferroviario meccanico', 'Strumento tecnico', 'XX secolo', 13),
('Campanello da stazione', 'Oggetto tecnico', 'XIX secolo', 13),
('Macchina obliteratrice di biglietti', 'Strumento tecnico', 'XX secolo', 13),
('Banco di manovra', 'Arredo tecnico', 'XX secolo', 13),
('Uniforme da capostazione', 'Abbigliamento storico', 'XX secolo', 13),
('Fischietto del macchinista', 'Oggetto tecnico', 'XX secolo', 13),
('Cartello “Ufficio Movimento”', 'Segnaletica storica', 'XX secolo', 13),
('Documento di servizio ferroviario', 'Documento storico', 'XIX secolo', 13),
('Valigia postale ferroviaria', 'Oggetto storico', 'XX secolo', 13),
('Modello di stazione in legno', 'Modello architettonico', 'XX secolo', 13),
('Tornio per ruote ferroviarie', 'Strumento meccanico', 'XX secolo', 13),
('Cartina delle linee piemontesi', 'Documento cartografico', 'XIX secolo', 13),
('Cabina di comando locomotiva elettrica', 'Reperto tecnico', 'XX secolo', 13),
('Quadro di segnalamento', 'Strumento tecnico', 'XX secolo', 13),
('Tavolo per telegrafo ferroviario', 'Arredo tecnico', 'XIX secolo', 13),
('Telegrafo ferroviario Morse', 'Strumento di comunicazione', 'XIX secolo', 13),
('Telefono da stazione', 'Strumento di comunicazione', 'XX secolo', 13),
('Biglietto ferroviario originale', 'Documento storico', 'XIX secolo', 13),
('Pannello con orari dei treni', 'Materiale informativo', 'XX secolo', 13),
('Chiave di scambio ferroviaria', 'Oggetto tecnico', 'XX secolo', 13),
('Divisa da macchinista FS', 'Abbigliamento storico', 'XX secolo', 13),
('Piastra di binario', 'Componente ferroviario', 'XX secolo', 13),
('Manuale tecnico per macchinisti', 'Documento tecnico', 'XX secolo', 13),
('Locomotiva elettrica E.626', 'Locomotiva', 'XX secolo', 13),
('Carro postale FS', 'Vagone', 'XX secolo', 13),
('Campanello di partenza', 'Oggetto tecnico', 'XIX secolo', 13),
('Olio per fanali ferroviari', 'Oggetto tecnico', 'XX secolo', 13),
('Divisa da controllore', 'Abbigliamento storico', 'XX secolo', 13),
('Fotografia storica della stazione di Torino', 'Fotografia', 'XIX secolo', 13),
('Tessera di dipendente FS', 'Documento', 'XX secolo', 13),
('Libro matricola personale FS', 'Documento amministrativo', 'XX secolo', 13),
('Ruota di locomotiva in ghisa', 'Componente meccanico', 'XIX secolo', 13),
('Banco di segnalamento elettrico', 'Strumento tecnico', 'XX secolo', 13),
('Bigliettatrice manuale', 'Strumento tecnico', 'XX secolo', 13),
('Fanale da locomotiva', 'Oggetto tecnico', 'XIX secolo', 13),
('Orologio da muro FS', 'Strumento meccanico', 'XX secolo', 13),
('Pannello didattico sulla trazione elettrica', 'Materiale espositivo', 'XX secolo', 13),
('Fotografia del deposito locomotive di Cuneo', 'Fotografia', 'XX secolo', 13),
('Manuale d’officina ferroviaria', 'Documento tecnico', 'XX secolo', 13),
('Ruota dentata di locomotiva a cremagliera', 'Componente meccanico', 'XX secolo', 13),
('Biglietto commemorativo per l’apertura del Frejus', 'Documento storico', 'XIX secolo', 13),
('Modello di locomotiva a vapore in ottone', 'Modello tecnico', 'XX secolo', 13),
('Divisa da capotreno', 'Abbigliamento storico', 'XX secolo', 13),
('Stendardo delle Ferrovie dello Stato', 'Oggetto commemorativo', 'XX secolo', 13);
/*!40000 ALTER TABLE `artefatto` ENABLE KEYS */;


/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;